const baseRedirects = [
  //wp-sitemap-posts-post-1.xml
  { source: '/a/product-category-product-acr-acr-black-series/:path*', destination: '/driver/acr/black', permanent: true },
  { source: '/a/klinik-rhyme-on-west-java/:path*', destination: '/berita/klinik-rhyme-west-java', permanent: true },
  { source: '/a/smex-2014/:path*', destination: '/berita/smex-2014', permanent: true },
  { source: '/a/grand-launching-rhyme/:path*', destination: '/berita/grand-launching-rhyme', permanent: true },
  { source: '/a/panlents-2014/:path*', destination: '/berita/palents-2014', permanent: true },
  { source: '/a/photo-competition-indonesia-merdeka/:path*', destination: '/berita/photo-competition-indonesia-merdeka', permanent: true },
  { source: '/a/klinik-rhyme-eastcentral-java-and-lampung/:path*', destination: '/berita/klinik-rhyme-east-java', permanent: true },
  { source: '/a/smex-2015/:path*', destination: '/berita/smex-2015', permanent: true },
  { source: '/a/smex-2016/:path*', destination: '/berita/road-to-smex-2016', permanent: true },
  { source: '/a/syawalan-komunitas-rental-sound-system-yogyakarta/:path*', destination: '/berita/syawalan-komunitas-rental-sound-system-yogyakarta', permanent: true },
  { source: '/a/smex-2016-2/:path*', destination: '/berita/smex-2016', permanent: true },
  { source: '/a/klinik-parade-sound-system-bersama-komunitas-komunitas-rental-tahun-2016/:path*', destination: '/berita/klinik-parade-sound-system', permanent: true },
  { source: '/a/smex-2017/:path*', destination: '/berita/road-to-smex-2017', permanent: true },
  { source: '/a/smex-2017-3/:path*', destination: '/berita/road-to-smex-2018', permanent: true },
  { source: '/a/smex-2017-2/:path*', destination: '/berita/smex-2017', permanent: true },
  { source: '/a/parade-sound-system-yogyakarta/:path*', destination: '/berita/parade-syawalan-sound-system-yogyakarta', permanent: true },
  { source: '/a/smex-2018/:path*', destination: '/berita/smex-2018', permanent: true },
  { source: '/a/syawalan-komunitas-rental-sound-system-yogyakarta-2018/:path*', destination: '/berita/syawalan-komunitas-rental-sound-system-yogyakarta-2018', permanent: true },
  { source: '/a/parade-sound-system-komunitas-tulungagung-psjta/:path*', destination: '/berita/parade-sound-system-komunitas-tulungagung-psjta', permanent: true },
  { source: '/a/suronan-pspt-pati-jawa-tengah/:path*', destination: '/berita/suronan-pspt-pati-jawa-tengah', permanent: true },
  { source: '/a/2038/:path*', destination: '/berita', permanent: true },
  { source: '/a/review-paguyupan-sound-system-jatim-pss-jatim-tuban/:path*', destination: '/berita/review-paguyupan-sound-system-jatim-pss-jatim-tuban', permanent: true },
  { source: '/a/review-paguyuban-sound-system-jombang-pssj/:path*', destination: '/berita/review-paguyuban-sound-system-jombang-pssj', permanent: true },
  { source: '/a/parade-syawalan-sound-system-yogyakarta/:path*', destination: '/berita/parade-syawalan-sound-system-yogyakarta', permanent: true },
  { source: '/a/review-parade-syawalan-sound-system-yogyakarta/:path*', destination: '/berita/review-parade-syawalan-sound-system-yogyakarta', permanent: true },
  { source: '/a/road-to-smex-2019/:path*', destination: '/berita/road-to-smex-2019', permanent: true },
  { source: '/a/smex-2019-2/:path*', destination: '/berita/smex-2019', permanent: true },
  { source: '/a/review-demak-expo-audio-iv/:path*', destination: '/berita/review-demak-expo-audio-iv', permanent: true },
  { source: '/a/review-blora-sound-community-bsc-season-iv/:path*', destination: '/berita/review-blora-sound-community-bsc-season-iv', permanent: true },
  { source: '/a/review-expo-bazar-syuronan-pati-2019/:path*', destination: '/berita/review-expo-bazar-syuronan-pati-2019', permanent: true },
  { source: '/a/demo-sound-rental-sharing-oleh-pssp-ke-vii-gempol-pasuruan/:path*', destination: '/berita/review-paguyuban-sound-system-pasuruan-pssp-ke-vii', permanent: true },
  { source: '/a/review-festival-sound-system-jenangan-kediri-3/:path*', destination: '/berita/review-festival-sound-system-jenangan-kediri-3', permanent: true },
  { source: '/a/pemberitahuan/:path*', destination: '/berita/pemberitahuan', permanent: true },
  { source: '/a/review-semarak-kolaborasi-sound-system-kediri-pss-jatim-pssjk-ssc/:path*', destination: '/berita/review-semarak-kolaborasi-sound-system-kediri-pss-jatim-pssjk-ssc', permanent: true },
  { source: '/a/review-suroan-kota-gresik-oleh-paguyuban-sound-system-gresik-pssg/:path*', destination: '/berita/review-suroan-kota-gresik-oleh-paguyuban-sound-system-gresik-pssg', permanent: true },
  { source: '/a/review-event-cek-sound-rhyme/:path*', destination: '/berita/cek-sound-rhyme', permanent: true },
  { source: '/a/review-kunjungan-pabrik-komunitas-probolinggo/:path*', destination: '/berita/review-kunjungan-pabrik-komunitas-probolinggo', permanent: true },
  { source: '/a/review-pameran-sound-system-oleh-komunitas-lamongan-paslab/:path*', destination: '/berita/review-pameran-sound-system-oleh-komunitas-lamongan-paslab', permanent: true },
  { source: '/a/review-pameran-sound-system-oleh-komunitas-jawa-timur-pss-jatim/:path*', destination: '/berita/review-pameran-sound-system-oleh-komunitas-jawa-timur-pss-jatim-exhibition-2', permanent: true },
  { source: '/a/review-pameran-sound-system-stb-sound-tugu-bersaudara-2-psjt-trenggalek/:path*', destination: '/berita/review-pameran-sound-system-stb-sound-tugu-bersaudara-2-psjt-trenggalek', permanent: true },
  { source: '/a/review-pameran-nguntir-bareng-paguyuban-sound-system-jombang-2/:path*', destination: '/berita/review-pameran-nguntir-bareng-paguyuban-sound-system-jombang-2', permanent: true },
  { source: '/a/highlight-event-sound-system-2022/:path*', destination: '/berita/highlight-event-sound-system-2022', permanent: true },
  { source: '/a/review-pameran-sound-system-mojokerto-pssm/:path*', destination: '/berita/review-pameran-sound-system-mojokerto-pssm', permanent: true },
  { source: '/a/cara-registrasi-my-sbe-2/:path*', destination: '/berita/cara-registrasi-my-sbe', permanent: true },
  { source: '/a/review-pameran-sound-system-syawalan-jogja-27-28-mei-2023/:path*', destination: '/berita/review-pameran-sound-system-syawalan-jogja-27-28-mei-2023', permanent: true },
  { source: '/a/perkenalan-produk-terbaru-acr-series-fabulous-excellent-di-syawalan-jogja-2023/:path*', destination: '/berita/perkenalan-produk-terbaru-acr-series-fabulous-excellent-di-syawalan-jogja-2023', permanent: true },
  { source: '/a/cek-sound-rhyme-bersama-ks3/:path*', destination: '/berita/cek-sound-rhyme-bersama-ks3', permanent: true },
  { source: '/a/review-pameran-sound-system-tuban-17-18-juni-2023/:path*', destination: '/berita/review-pameran-sound-system-tuban-17-18-juni-2023', permanent: true },
  { source: '/a/smex-2023/:path*', destination: '/berita/smex-2023', permanent: true },
  { source: '/a/speaker-double-magnet-18in-113188-sw-fabulous/:path*', destination: '/berita/speaker-double-magnet-18in-113188-sw-fabulous', permanent: true },
  { source: '/a/laporan-pameran-sound-system-pspt-pati-12-13-agustus-2023/:path*', destination: '/berita/laporan-pameran-sound-system-pspt-pati-12-13-agustus-2023', permanent: true },
  { source: '/a/laporan-pameran-sound-system-psds-demak-29-30-juli-2023/:path*', destination: '/berita/laporan-pameran-sound-system-psds-demak-29-30-juli-2023', permanent: true },
  { source: '/a/undian-poin-my-sbe-2023/:path*', destination: '/berita/undian-poin-my-sbe-2023', permanent: true },
  { source: '/a/speaker-terbaru-dari-deluxe-acr-series-18in-18710-dlx-15in-15710-dlx/:path*', destination: '/berita/speaker-terbaru-dari-deluxe-acr-series-18in-18710-dlx-15in-15710-dlx', permanent: true },
  { source: '/a/list-produk-yang-tidak-akan-diproduksi-lagi-pada-akhir-tahun-2023/:path*', destination: '/berita/list-produk-yang-tidak-akan-diproduksi-lagi-pada-akhir-tahun-2023/:path*', permanent: true },
  { source: '/a/merchandise-eksklusif-untuk-kalian-para-juara-acr/:path*', destination: '/berita/merchandise-eksklusif-untuk-kalian-para-juara-acr', permanent: true },
  { source: '/a/pameran-texass-trenggalek-25-26-november-2023/:path*', destination: '/berita/pameran-texass-trenggalek-25-26-november-2023', permanent: true },
  { source: '/a/best-seller-di-kelasnya-6in-array-1550-dan-10in-75105-fab/:path*', destination: '/berita/best-seller-di-kelasnya-6in-array-1550-dan-10in-75105-fab', permanent: true },
  { source: '/a/acr-jingle-competition-2024/:path*', destination: '/berita/acr-jingle-competition-2024', permanent: true },
  { source: '/a/pertama-di-dunia-speaker-dengan-heatsink-luar/:path*', destination: '/berita/pertama-di-indonesia-speaker-dengan-heatsink-diluar-terbaru-dari-acr', permanent: true },
  { source: '/a/langkahmengikuti-undian-poin-my-sbe/:path*', destination: '/berita/langkah-mengikuti-undian-poin-my-sbe', permanent: true },
  { source: '/a/isi-survey-dan-dapatkan-speakernya/:path*', destination: '/berita/isi-survey-dan-dapatkan-speakernya', permanent: true },
  { source: '/a/gebyar-hadiah-sbe-link-2024/:path*', destination: '/berita/gebyar-hadiah-sbe-link-2024', permanent: true },
  { source: '/a/pameran-sound-system-psst-paguyuban-sound-system-tulungagung-pada-11-12-mei-2024/:path*', destination: '/berita/pameran-sound-system-psst-paguyuban-sound-system-tulungagung-pada-11-12-mei-2024', permanent: true },
  { source: '/a/pameran-sound-system-pssj-jombang-18-19-mei-2024/:path*', destination: '/berita/pameran-sound-system-pssj-jombang-18-19-mei-2024', permanent: true },
  { source: '/a/pameran-sound-system-kstb-komunitas-sound-sistem-tretan-bangkalan-bangkalan-horeg-festival-2024-pada-25-26-mei-2024/:path*', destination: '/berita/pameran-sound-system-kstb-komunitas-sound-sistem-tretan-bangkalan-bangkalan-horeg-festival-2024-pada-25-26-mei-2024', permanent: true },
  { source: '/a/smex-2024/:path*', destination: '/berita/smex-surabaya-2024', permanent: true },
  { source: '/a/coming-soon-acr-black-series/:path*', destination: '/berita/coming-soon-speaker-lokal-harga-murah-acr-black-series', permanent: true },
  { source: '/a/acr-rhyme-desibel-di-acara-paguyuban-sound-system-pasuruan-2024/:path*', destination: '/berita/acr-rhyme-desibel-di-acara-paguyuban-sound-system-pasuruan-2024', permanent: true },
  { source: '/a/acr-rhyme-desibel-di-acara-paguyuban-sound-system-lampung-timur-psslt/:path*', destination: '/berita/acr-rhyme-desibel-di-acara-paguyuban-sound-system-lampung-timur-psslt', permanent: true },
  { source: '/a/acr-rhyme-desibel-di-acara-nguntir-bareng-anniversary-ke-5-ppssn/:path*', destination: '/berita/acr-rhyme-desibel-di-acara-nguntir-bareng-anniversary-ke-5-ppssn', permanent: true },
  { source: '/a/kunjungan-psst-ke-pabrik-sinar-baja-electric/:path*', destination: '/berita/kunjungan-psst-ke-pabrik-sinar-baja-electric', permanent: true },
  { source: '/a/lomba-konten-untuk-para-dealer-resmi-sbe/:path*', destination: '/berita/lomba-konten-untuk-para-dealer-resmi-sbe', permanent: true },
  { source: '/a/keseruan-acr-rhyme-desibel-di-acara-pro-avl-indonesia-expo-2024/:path*', destination: '/berita/keseruan-acr-rhyme-desibel-di-acara-pro-avl-indonesia-expo-2024', permanent: true },
  { source: '/a/acr-rhyme-desibel-tampil-memukau-di-acara-gebyar-kesenian-bantengan-malang/:path*', destination: '/berita/acr-rhyme-desibel-tampil-memukau-di-acara-gebyar-kesenian-bantengan-malang', permanent: true },
  { source: '/a/pesona-rm-226-la-dan-rm-1283-sb-saat-tes-sound-di-pabrik-sinar-baja-electric-bersama-ppssn-ngawi/:path*', destination: '/berita/pesona-rm-226-la-dan-rm-1283-sb-saat-tes-sound-di-pabrik-sinar-baja-electric-bersama-ppssn-ngawi', permanent: true },
  { source: '/a/produk-lokal-kebanggaan-indonesia-acr-rhyme-desibel-hadir-di-javme-2024/:path*', destination: '/berita/produk-lokal-kebanggaan-indonesia-acr-rhyme-desibel-hadir-di-javme-2024', permanent: true },
  { source: '/a/produk-lokal-karya-anak-bangsa-acr-rhyme-desibel-tampil-di-acara-pss-jatim-exhibtion-3-2024/:path*', destination: '/berita/produk-lokal-karya-anak-bangsa-acr-rhyme-desibel-tampil-di-acara-pss-jatim-exhibtion-3-2024', permanent: true },
  { source: '/a/acr-bagi-bagi-thr-melalui-event-acr-jingle-competition-2025/:path*', destination: '/berita/acr-bagi-bagi-thr-melalui-event-acr-jingle-competition-2025', permanent: true },
  { source: '/a/kolaborasi-ekslusif-sinar-baja-electric-dengan-brewog/:path*', destination: '/berita/kolaborasi-ekslusif-sinar-baja-electric-dengan-brewog', permanent: true },
  { source: '/a/sparepart-acr-yang-tersedia-di-dealer-resmi/:path*', destination: '/berita/sparepart-acr-yang-tersedia-di-dealer-resmi', permanent: true },

  //wp-sitemap-posts-page-1.xml
  { source: '/sample-page', destination: '/tentang-kami', permanent: true },
  { source: '/contact-us', destination: '/kontak', permanent: true },
  { source: '/events', destination: '/berita', permanent: true },
  { source: '/news-event', destination: '/berita', permanent: true },
  { source: '/product', destination: '/driver', permanent: true },
  { source: '/product/acr', destination: '/driver/acr', permanent: true },
  { source: '/product/curve', destination: '/driver/curve', permanent: true },
  { source: '/product/acr/tweeter-hifi', destination: '/driver/acr/pro/tweeter', permanent: true },
  { source: '/product/acr/fullrange-hifi', destination: '/driver/acr/pro/full-range', permanent: true },
  // { source: '/product/acr/middle-hifi', destination: '/', permanent: true },
  { source: '/product/acr/woofer-hifi', destination: '/driver/acr/pro/woofer', permanent: true },
  { source: '/product/acr/ceiling-speaker', destination: '/driver/acr/pro/ceiling', permanent: true },
  // { source: '/product/acr/speakers-pa', destination: '/', permanent: true },
  { source: '/product/acr/compression-driver-pa', destination: '/driver/acr/pro/compression-driver', permanent: true },
  { source: '/product/acr/horn-pa', destination: '/driver/acr/pro/horn', permanent: true },
  { source: '/product/acr/recone-kit-pa', destination: '/sparepart', permanent: true },
  { source: '/product/curve/compression-driver', destination: '/driver/acr/pro/compression-driver', permanent: true },
  { source: '/product/curve/speaker-pa', destination: '/driver/curve', permanent: true },
  // { source: '/links', destination: '/', permanent: true },
  // { source: '/cart', destination: '/', permanent: true },
  // { source: '/my-account', destination: '/', permanent: true },
  { source: '/product/acr/recone-kit-pa/subwoofers', destination: '/sparepart', permanent: true },
  { source: '/discontinue-product', destination: '/driver/discontinued', permanent: true },
  { source: '/product/desibel', destination: '/driver/desibel', permanent: true },
  { source: '/catalogue', destination: '/katalog', permanent: true },
  { source: '/black-series', destination: '/driver/black', permanent: true },
  { source: '/subwoofer', destination: '/driver/subwoofer', permanent: true },
  { source: '/subwoofer-2', destination: '/driver/subwoofer', permanent: true },
  { source: '/compression', destination: '/driver/compression-driver', permanent: true },
  { source: '/woofer', destination: '/driver/woofer', permanent: true },
  { source: '/fullrange', destination: '/driver/full-range', permanent: true },

  //wp-sitemap-posts-page-1.xml per page
  { source: '/product/acr/page/:path*', destination: '/driver/acr', permanent: true },
  { source: '/product/curve/page/:path*', destination: '/driver/curve', permanent: true },
  { source: '/product/acr/tweeter-hifi/page/:path*', destination: '/driver/acr/pro/tweeter', permanent: true },
  { source: '/product/acr/fullrange-hifi/page/:path*', destination: '/driver/acr/pro/full-range', permanent: true },
  // { source: '/product/acr/middle-hifi/page/:path*', destination: '/', permanent: true },
  { source: '/product/acr/woofer-hifi/page/:path*', destination: '/driver/acr/pro/woofer', permanent: true },
  { source: '/product/acr/ceiling-speaker/page/:path*', destination: '/driver/acr/pro/ceiling', permanent: true },
  // { source: '/product/acr/speakers-pa/page/:path*', destination: '/', permanent: true },
  { source: '/product/acr/compression-driver-pa/page/:path*', destination: '/driver/acr/pro/compression-driver', permanent: true },
  { source: '/product/acr/horn-pa/page/:path*', destination: '/driver/acr/pro/horn', permanent: true },
  { source: '/product/acr/recone-kit-pa/page/:path*', destination: '/sparepart', permanent: true },
  { source: '/product/curve/compression-driver/page/:path*', destination: '/driver/acr/pro/compression-driver', permanent: true },
  { source: '/product/curve/speaker-pa/page/:path*', destination: '/driver/curve', permanent: true },
  { source: '/product/acr/recone-kit-pa/subwoofers/page/:path*', destination: '/sparepart', permanent: true },
  { source: '/discontinue-product/page/:path*', destination: '/driver/discontinued', permanent: true },
  { source: '/product/desibel/page/:path*', destination: '/driver/desibel', permanent: true },
  { source: '/black-series/page/:path*', destination: '/driver/black', permanent: true },
  { source: '/subwoofer/page/:path*', destination: '/driver/subwoofer', permanent: true },
  { source: '/subwoofer-2/page/:path*', destination: '/driver/subwoofer', permanent: true },
  { source: '/compression/page/:path*', destination: '/driver/compression-driver', permanent: true },
  { source: '/woofer/page/:path*', destination: '/driver/woofer', permanent: true },
  { source: '/fullrange/page/:path*', destination: '/driver/full-range', permanent: true },

  //wp-sitemap-posts-product-1.xml
  { source: '/product/6-603-acr', destination: '/produk/cs-603-acr', permanent: true },
  { source: '/product/6-605-acr', destination: '/produk/cs-605-acr', permanent: true },
  { source: '/product/15-38h156scf-acr-special-new', destination: '/produk/38h156scf-acr-special-new', permanent: true },
  { source: '/product/horn-ph-225-acr', destination: '/produk/horn-h-225-acr', permanent: true },
  { source: '/product/horn-ph-250-acr', destination: '/produk/horn-h-250-acr', permanent: true },
  { source: '/product/horn-2525-acr', destination: '/produk/horn-2525-acr', permanent: true },
  { source: '/product/horn-2538-acr', destination: '/produk/horn-2538-acr', permanent: true },
  { source: '/product/compression-driver-1-acr', destination: '/produk/cd-250c1-08f-mk1-by-acr', permanent: true },
  { source: '/product/compression-driver-2-acr', destination: '/produk/cd-250t1-08f-mk1-by-acr', permanent: true },
  { source: '/product/compression-driver-6-acr', destination: '/produk/cd-380c1-08f-cd-6-acr', permanent: true },
  { source: '/product/compression-driver-9-acr', destination: '/produk/cd-340t1-08f-cd-9-acr', permanent: true },
  { source: '/product/compression-driver-9b-acr', destination: '/produk/cd-340t1b-08f-mk1-by-acr', permanent: true },
  { source: '/product/compression-driver-10-acr', destination: '/produk/cd-250p1-08f-cd-10-acr', permanent: true },
  { source: '/product/12-1280-acr-black-magic', destination: '/produk/1280-acr-black-magic', permanent: true },
  { source: '/product/15-1590-acr-black-magic', destination: '/produk/1590-acr-black-magic', permanent: true },
  { source: '/product/12-cl-1238-pc-acr-classic-new', destination: '/produk/cl-1238-pc-acr-classic-new', permanent: true },
  { source: '/product/12-cl-1240-pa-acr-classic', destination: '/produk/1240-mk1-pa-acr-classic', permanent: true },
  { source: '/product/15-far-1580-pa-acr-classic', destination: '/produk/far-1580-pa-acr-classic', permanent: true },
  { source: '/product/12-pa-12900-premier-by-acr', destination: '/produk/pa-12900-premier-by-acr', permanent: true },
  { source: '/product/15-15737-deluxe-by-acr', destination: '/produk/15737-deluxe-by-acr', permanent: true },
  { source: '/product/18-18737-deluxe-by-acr', destination: '/produk/18737-deluxe-by-acr', permanent: true },
  { source: '/product/cd-4-excellent-by-acr', destination: '/produk/cd-440t1-08-cd-4-excellent-by-acr', permanent: true },
  { source: '/product/cd-4b-excellent-by-acr', destination: '/produk/cd-440t1b-08-cd-4b-excellent-by-acr', permanent: true },
  { source: '/product/cd-7-mk-ii-excellent-by-acr', destination: '/produk/cd-7-mk2-excellent-by-acr', permanent: true },
  { source: '/product/10-pa-10880-mk-ii-excellent-by-acr', destination: '/produk/pa-10880-mk2-excel-by-acr', permanent: true },
  { source: '/product/12-pa-12880-mk-ii-excellent-by-acr', destination: '/produk/pa-12880-mk2-excel-by-acr', permanent: true },
  { source: '/product/15-pa-15838-excellent-by-acr', destination: '/produk/pa-15838-excel-by-acr', permanent: true },
  { source: '/product/15-pa-15753-m-excellent-by-acr', destination: '/produk/pa-15753-w-mk1-excel-by-acr', permanent: true },
  { source: '/product/18-pa-18838-excellent-by-acr', destination: '/produk/pa-18838-excel-by-acr', permanent: true },
  { source: '/product/cd-750tr15b-08-fabulous-by-acr', destination: '/produk/cd-750tr15b-08-fabulous-by-acr', permanent: true },
  { source: '/product/8-array-2050-m-fabulous-by-acr', destination: '/produk/array-2050-m-fab-by-acr', permanent: true },
  { source: '/product/8-array-20601-m-fabulous-by-acr', destination: '/produk/array-20601-m-fab-by-acr', permanent: true },
  { source: '/product/10-array-2560-m-fabulous-by-acr', destination: '/produk/array-2560-m-fab-by-acr', permanent: true },
  { source: '/product/12-array-3060-m-fabulous-by-acr', destination: '/produk/array-3060-m-fab-by-acr', permanent: true },
  { source: '/product/15-pa-75155-m-fabulous-by-acr', destination: '/produk/pa-75155-w-mk1-fab-by-acr', permanent: true },
  { source: '/product/18-pa-113186-sw-fabulous-by-acr', destination: '/produk/pa-113186-sw-fab-by-acr', permanent: true },
  { source: '/product/21-pa-113212-sw-fabulous-by-acr', destination: '/produk/pa-113212-sw-fab-by-acr', permanent: true },
  { source: '/product/5-538-curve', destination: '/produk/538-curve', permanent: true },
  { source: '/product/6-618-curve', destination: '/produk/618-curve', permanent: true },
  { source: '/product/6-638-curve-black', destination: '/produk/638-curve', permanent: true },
  { source: '/product/6-648-curve-black', destination: '/produk/648-curve-black', permanent: true },
  { source: '/product/8-838-curve-black', destination: '/produk/838-curve', permanent: true },
  { source: '/product/8-848-curve-black', destination: '/produk/848-curve-black', permanent: true },
  { source: '/product/8-858-curve', destination: '/produk/858-curve', permanent: true },
  { source: '/product/8-818-w-curve', destination: '/produk/818-w-curve', permanent: true },
  { source: '/product/10-25h100suwpp-curve', destination: '/produk/25h100suwpp-curve-pls', permanent: true },
  { source: '/product/10-c-1018-hw-curve', destination: '/produk/c-1018-hw-curve', permanent: true },
  { source: '/product/12-c-1230-pa-curve', destination: '/produk/c-1230-pa-curve', permanent: true },
  { source: '/product/15-38h156scf-curve', destination: '/produk/38h156scf-curve', permanent: true },
  { source: '/product/12-c-1230-pa-special-new-mk-ii', destination: '/produk/c-1230-pa-mk2-special-new', permanent: true },
  { source: '/product/8-c-810-dfh-acr', destination: '/produk/c-810-dfh-acr', permanent: true },
  { source: '/product/10-c-1018-hw-acr-pro-new', destination: '/produk/c-1018-hw-acr-pro-new', permanent: true },
  { source: '/product/12-acr-1225-new', destination: '/produk/acr-1225-new', permanent: true },
  { source: '/product/12-1230-black', destination: '/produk/1230-black', permanent: true },
  { source: '/product/15-acr-15200-new', destination: '/produk/acr-15200-new', permanent: true },
  { source: '/product/15-acr-15400-pro-new', destination: '/produk/acr-15400-pro-new', permanent: true },
  { source: '/product/15-acr-15500-black-platinum', destination: '/produk/acr-15500-black-platinum', permanent: true },
  { source: '/product/15-acr-15600-black', destination: '/produk/acr-15600-black', permanent: true },
  { source: '/product/6-array-5061-m-fabulous-by-acr', destination: '/produk/array-5061-m-fab-by-acr', permanent: true },
  { source: '/product/12-pa-75124-w-n-fabulous-by-acr', destination: '/produk/pa-75124-w-n-fab-by-acr', permanent: true },
  { source: '/product/18-pa-113182-mk-ii-sw-fabulous-by-acr', destination: '/produk/pa-113182-mk2-sw-fab-by-acr', permanent: true },
  { source: '/product/18-pa-100187-sw-fabulous-by-acr', destination: '/produk/pa-100187-sw-fab-by-acr', permanent: true },
  { source: '/product/18-pa-113187-sw-fabulous-by-acr', destination: '/produk/pa-113187-sw-fab-by-acr', permanent: true },
  { source: '/product/18-pa-127187-sw-fabulous-by-acr', destination: '/produk/pa-127187-sw-fab-by-acr', permanent: true },
  { source: '/product/21-pa-127212-sw-fab-by-acr', destination: '/produk/pa-127212-sw-fab-by-acr', permanent: true },
  { source: '/product/18-18700-mk-1-dlx-by-acr', destination: '/produk/pa-18700-mk1-deluxe-by-acr', permanent: true },
  { source: '/product/18-pa-18900-mk-1-pre-by-acr', destination: '/produk/pa-18900-mk1-pre-by-acr', permanent: true },
  { source: '/product/18-pa-18890-mk-4-excel-by-acr', destination: '/produk/pa-18890-mk4-excel-by-acr', permanent: true },
  { source: '/product/15-pa-113156-sw-fab-by-acr', destination: '/produk/pa-113156-sw-fab-by-acr', permanent: true },
  { source: '/product/18-pa-113183-sw-mk-2-fab-by-acr', destination: '/produk/pa-113183-sw-mk2-fab-by-acr', permanent: true },
  { source: '/product/15-pa-15900-mk-1-pre-by-acr', destination: '/produk/pa-15900-mk1-pre-by-acr', permanent: true },
  { source: '/product/15-pa-15900-mk-1-pre-by-acr-2', destination: '/produk/15700-mk1-deluxe-by-acr', permanent: true },
  { source: '/product/15-pa-15890-mk4-excel-by-acr', destination: '/produk/pa-15890-mk4-excel-by-acr', permanent: true },
  { source: '/product/15-pa-100182-mk2-sw-fab-by-acr', destination: '/produk/pa-100182-mk2-sw-fab-by-acr', permanent: true },
  { source: '/product/15-pa-100152-mk1-sw-fab-by-acr', destination: '/produk/pa-100152-mk1-sw-fab-by-acr', permanent: true },
  { source: '/product/15-pa-75157-w-n-fab-by-acr', destination: '/produk/pa-75157-w-n-fab-by-acr', permanent: true },
  { source: '/product/15-pa-75127-w-n-fab-by-acr', destination: '/produk/pa-75127-w-n-fab-by-acr', permanent: true },
  { source: '/product/12-pa-75125-m-fab-by-acr', destination: '/produk/pa-75125-m-fab-by-acr', permanent: true },
  { source: '/product/21-ax-21800-mk1-black-grand-acr', destination: '/produk/ax-21800-mk1-black-grand-acr', permanent: true },
  { source: '/product/12-1280-mk1-acr-black-magic', destination: '/produk/1280-mk1-acr-black-magic', permanent: true },
  { source: '/product/10%e2%80%b3-array-6510-m-mk1-fab-by-acr', destination: '/produk/array-6510-m-mk1-fab-by-acr', permanent: true },
  { source: '/product/cd-650tr15b-08f-fab', destination: '/produk/cd-650tr15b-08f-fabulous', permanent: true },
  { source: '/product/cd-440pk1-04n-fabulous-series', destination: '/produk/cd-440pk1-04n-fabulous', permanent: true },
  { source: '/product/12-pa-65125-m-fabulous-by-acr', destination: '/produk/pa-65125-m-fab-by-acr', permanent: true },
  { source: '/product/cd-440pk1b-08f-fabulous-series', destination: '/produk/cd-440pk1b-08f-fabulous', permanent: true },
  { source: '/product/cd-440k1b-08f-fabulous-series', destination: '/produk/cd-440k1b-08f-fabulous', permanent: true },
  { source: '/product/cd-340pk1b-08f-fabulous-series', destination: '/produk/cd-340pk1b-08f-fabulous', permanent: true },
  { source: '/product/cd-250pb1b-08f-fabulous-series', destination: '/produk/cd-250p1b-08f-fabulous', permanent: true },
  { source: '/product/18-pa-188175-excellent-by-acr', destination: '/produk/pa-188175-excel-by-acr', permanent: true },
  { source: '/product/12-pa-127150-deluxe-by-acr', destination: '/produk/127150-deluxe-by-acr', permanent: true },
  { source: '/product/15-157165-deluxe-by-acr', destination: '/produk/157165-deluxe-by-acr', permanent: true },
  { source: '/product/18-187175-deluxe-by-acr', destination: '/produk/187175-deluxe-by-acr', permanent: true },
  { source: '/product/cd-44-desibel', destination: '/produk/cd-44-desibel', permanent: true },
  { source: '/product/12-30h120srw38b-acr-pro', destination: '/produk/30h120srw38b-mk1-acr-pro', permanent: true },
  { source: '/product/cd-44b-desibel', destination: '/produk/cd-44b-desibel', permanent: true },
  { source: '/product/15in-381006-desibel', destination: '/produk/381006-desibel', permanent: true },
  { source: '/product/18in-451006-desibel', destination: '/produk/451006-desibel', permanent: true },
  { source: '/product/10in-25601-desibel', destination: '/produk/25601-desibel', permanent: true },
  { source: '/product/12in-30601-desibel', destination: '/produk/30601-desibel', permanent: true },
  { source: '/product/15in-38601-desibel', destination: '/produk/38601-desibel', permanent: true },
  { source: '/product/cd-34-desibel', destination: '/produk/cd-34-desibel', permanent: true },
  { source: '/product/15-acr-15600-black-2', destination: '/produk/acr-15600plus-black', permanent: true },
  { source: '/product/cd-65-desibel', destination: '/produk/cd-65-desibel', permanent: true },
  { source: '/product/12-30h120srw38b-curve-pls', destination: '/produk/30h120srw38b-curve-pls', permanent: true },
  { source: '/product/15-38h156scf-mk-curve', destination: '/produk/38h156scf-mk-curve', permanent: true },
  { source: '/product/12-c-1230-pa-curve-pls', destination: '/produk/c-1230-pa-curve-pls', permanent: true },
  { source: '/product/18-pa-188127-excel-by-acr', destination: '/produk/pa-188127-excel-by-acr', permanent: true },
  { source: '/product/6-array-1550-m-fab', destination: '/produk/array-1550-m-fab', permanent: true },
  { source: '/product/10-75105-fab', destination: '/produk/75105-fab', permanent: true },
  { source: '/product/12-pa-12880-mk3-excel-by-acr', destination: '/produk/pa-12880-mk3-excel-by-acr', permanent: true },
  { source: '/product/10-pa-10880-mk3-excel-by-acr', destination: '/produk/pa-10880-mk3-excel-by-acr', permanent: true },
  { source: '/product/18-pa-113188-sw-fab-by-acr', destination: '/produk/pa-113188-sw-fab-by-acr', permanent: true },
  { source: '/product/18-18710-dlx', destination: '/produk/18710-dlx', permanent: true },
  { source: '/product/15-15710-dlx', destination: '/produk/15710-dlx', permanent: true },
  { source: '/product/cd-51-desibel', destination: '/produk/cd-51-desibel', permanent: true },
  { source: '/product/8in-20381-desibel', destination: '/produk/20381-desibel', permanent: true },
  { source: '/product/15%e2%80%b3-pa-100152-mk2-sw-fab-by-acr', destination: '/produk/pa-100152-mk2-sw-fab-by-acr', permanent: true },
  { source: '/product/18%e2%80%b3-pa-100182-mk3-sw-fab-by-acr', destination: '/produk/pa-100182-mk3-sw-fab-by-acr', permanent: true },
  { source: '/product/15-1575-black', destination: '/produk/15750-black', permanent: true },
  { source: '/product/cd-251-black-series', destination: '/produk/cd-251-black', permanent: true },
  { source: '/product/10-1050-black', destination: '/produk/10500-black', permanent: true },
  { source: '/product/15-15100-black', destination: '/produk/15100-black', permanent: true },
  { source: '/product/18-18100-black', destination: '/produk/18100-black', permanent: true },
  { source: '/product/12-1250-black', destination: '/produk/12500-black', permanent: true },
  { source: '/product/12-1225-mk1-new', destination: '/produk/1225-mk1-new', permanent: true },
  { source: '/product/12-1230-mk1-black', destination: '/produk/1230-mk1-black', permanent: true },
  { source: '/product/8in-array-8388-m-fab', destination: '/produk/array-8388-m-fab-limited-edition', permanent: true },
  { source: '/product/12-1238-mk1-pc-acr-classic-new', destination: '/produk/1238-mk1-pc-acr-classic-new', permanent: true },
  { source: '/product/12in-1240-mk2-pa-classic', destination: '/produk/1240-mk2-pa-classic', permanent: true },
  { source: '/product/8-array-8850-m-limited-edition', destination: '/produk/array-8850-m-limited-edition', permanent: true },
  { source: '/product/18in-pa-127188-sw', destination: '/produk/pa-127188-sw', permanent: true },
  { source: '/product/18in-451006-mk1-desibel', destination: '/produk/451006-mk1-desibel', permanent: true },
  { source: '/product/15in-381006-mk1-desibel', destination: '/produk/381006-mk1-desibel', permanent: true },
  { source: '/product/12in-pa-100122-w-fab-acr-series', destination: '/produk/pa-100122-w-fab-acr-series', permanent: true },
  { source: '/product/15in-15500-mk1-black', destination: '/produk/15500-mk1-black', permanent: true },
  { source: '/product/15in-15200-mk1', destination: '/produk/15200-mk1', permanent: true },
  { source: '/product/6in-array-5061-mk1-m-fab', destination: '/produk/array-5061-mk1-m-fab', permanent: true },
  { source: '/product/18-pa-113182-mk3-sw-fab-by-acr', destination: '/produk/pa-113182-mk3-sw-fab-by-acr', permanent: true },
  { source: '/product/18-pa-113186-mk1-sw', destination: '/produk/pa-113186-mk1-sw', permanent: true },
  { source: '/product/15-pa-113156-mk1-sw', destination: '/produk/pa-113156-mk1-sw', permanent: true },

  //wp-sitemap-posts-3d-flip-book-1.xml
  { source: '/a/3d-flip-book/oem-automotive-catalog', destination: '/katalog', permanent: true },
  { source: '/a/3d-flip-book/katalog-acr', destination: '/katalog', permanent: true },
  { source: '/a/3d-flip-book/katalog-acr-series', destination: '/katalog', permanent: true },
  { source: '/a/3d-flip-book/katalog-acr-fabulous', destination: '/katalog', permanent: true },
  { source: '/a/3d-flip-book/katalog-desibel-2', destination: '/katalog', permanent: true },

  //wp-sitemap-posts-mailpoet_page-1.xml
  // { source: '/?mailpoet_page=subscriptions', destination: '/', permanent: true },

  //wp-sitemap-taxonomies-category-1.xml
  { source: '/a/category/news-events/', destination: '/berita', permanent: true },
  { source: '/a/category/home-slide/', destination: '/', permanent: true },

  //wp-sitemap-taxonomies-product_cat-1.xml
  { source: '/product-category/product/acr-acr/pa-acr', destination: '/driver/acr/pro', permanent: true },
  { source: '/product-category/product/acr-acr/pa-black-magic', destination: '/driver/acr/black-magic', permanent: true },
  { source: '/product-category/product/acr-acr/pa-classic', destination: '/driver/acr/classic', permanent: true },
  { source: '/product-category/product/acr-acr/pa-premier-acr', destination: '/driver/acr/premier', permanent: true },
  { source: '/product-category/product/acr-acr/pa-deluxe', destination: '/driver/acr/deluxe', permanent: true },
  { source: '/product-category/product/acr-acr/pa-excellent', destination: '/driver/acr/excellent', permanent: true },
  { source: '/product-category/product/acr-acr/pa-fabulous', destination: '/driver/acr/fabulous', permanent: true },
  { source: '/product-category/product/curve', destination: '/driver/curve', permanent: true },
  { source: '/product-category/product/acr-acr', destination: '/driver/acr', permanent: true },
  { source: '/product-category/product', destination: '/driver', permanent: true },
  { source: '/product-category/type/subwoofer', destination: '/driver/subwoofer', permanent: true },
  { source: '/product-category/type/woofer', destination: '/driver/woofer', permanent: true },
  { source: '/product-category/type/tweeter', destination: '/driver/tweeter', permanent: true },
  { source: '/product-category/type/midbass', destination: '/driver/midbass', permanent: true },
  { source: '/product-category/type/midrange', destination: '/driver/midrange', permanent: true },
  { source: '/product-category/type/horn', destination: '/driver/horn', permanent: true },
  { source: '/product-category/type/ceiling', destination: '/driver/ceiling', permanent: true },
  { source: '/product-category/type', destination: '/driver', permanent: true },
  { source: '/product-category/product/acr-acr/pa-fabulous/subwoofer-pa-fabulous', destination: '/driver/acr/fabulous/subwoofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-fabulous/woofer-pa-fabulous', destination: '/driver/acr/fabulous/woofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-fabulous/midrange-pa-fabulous', destination: '/driver/acr/fabulous/midrange', permanent: true },
  { source: '/product-category/product/acr-acr/pa-fabulous/tweeter-pa-fabulous', destination: '/driver/acr/fabulous/tweeter', permanent: true },
  { source: '/product-category/product/acr-acr/pa-excellent/tweeter-pa-excellent', destination: '/driver/acr/excellent/tweeter', permanent: true },
  { source: '/product-category/product/acr-acr/pa-excellent/woofer-pa-excellent', destination: '/driver/acr/excellent/woofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-excellent/subwoofer-pa-excellent', destination: '/driver/acr/excellent/subwoofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-deluxe/subwoofer-pa-deluxe', destination: '/driver/acr/deluxe/subwoofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-premier-acr/woofer-pa-premier-acr', destination: '/driver/acr/premier/woofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-premier-acr/subwoofer-pa-premier-acr', destination: '/driver/acr/premier/subwoofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-classic/fullrange-pa-classic', destination: '/driver/acr/classic/full-range', permanent: true },
  { source: '/product-category/product/acr-acr/pa-black-magic/fullrange-pa-black-magic', destination: '/driver/acr/black-magic/full-range', permanent: true },
  { source: '/product-category/product/acr-acr/pa-acr/horn-pa-acr', destination: '/driver/acr/pro/horn', permanent: true },
  { source: '/product-category/product/acr-acr/pa-acr/tweeter-pa-acr', destination: '/driver/acr/pro/compression-driver', permanent: true },
  { source: '/product-category/product/acr-acr/pa-acr/fullrange-pa-acr', destination: '/driver/acr/pro/full-range', permanent: true },
  { source: '/product-category/product/acr-acr/pa-acr/woofer-pa-acr', destination: '/driver/acr/pro/woofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-acr/subwoofer-pa-acr', destination: '/driver/acr/pro/subwoofer', permanent: true },
  { source: '/product-category/product/curve/woofer-curve', destination: '/driver/curve/woofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-deluxe/woofer-pa-deluxe', destination: '/driver/acr/deluxe/woofer', permanent: true },
  { source: '/product-category/discontinued', destination: '/driver/discontinued', permanent: true },
  { source: '/product-category/discontinued/acr-discontinued', destination: '/driver/acr/pro/discontinued', permanent: true },
  { source: '/product-category/desibel', destination: '/driver/desibel', permanent: true },
  { source: '/product-category/desibel/desibel-tweeter', destination: '/driver/desibel/tweeter', permanent: true },
  { source: '/product-category/desibel/desibel-woofer', destination: '/driver/desibel/woofer', permanent: true },
  { source: '/product-category/desibel/desibel-subwoofer', destination: '/driver/desibel/subwoofer', permanent: true },
  { source: '/product-category/product/curve/fullrange-curve', destination: '/driver/curve/full-range', permanent: true },
  { source: '/product-category/type/fullrange', destination: '/driver/full-range', permanent: true },
  { source: '/product-category/desibel/desibel-desibel', destination: '/driver/desibel', permanent: true },
  { source: '/product-category/product/acr-acr/black-series', destination: '/driver/acr/black', permanent: true },
  { source: '/product-category/product/acr-acr/black-series/woofer-black-series', destination: '/driver/acr/black/woofer', permanent: true },
  { source: '/product-category/product/acr-acr/black-series/subwoofer-black-series', destination: '/driver/acr/black/subwoofer', permanent: true },
  { source: '/product-category/product/acr-acr/black-series/compression', destination: '/driver/acr/black/compression-driver', permanent: true },
  { source: '/product-category/product/acr-acr/black-series/fullrange-black-series', destination: '/driver/acr/black/full-range', permanent: true },
  { source: '/product-category/carousel_featured', destination: '/', permanent: true },
  
  //wp-sitemap-taxonomies-product_cat-1.xml per page
  { source: '/product-category/product/acr-acr/pa-acr/page/:path*', destination: '/driver/acr/pro', permanent: true },
  { source: '/product-category/product/acr-acr/pa-black-magic/page/:path*', destination: '/driver/acr/black-magic', permanent: true },
  { source: '/product-category/product/acr-acr/pa-classic/page/:path*', destination: '/driver/acr/classic', permanent: true },
  { source: '/product-category/product/acr-acr/pa-premier-acr/page/:path*', destination: '/driver/acr/premier', permanent: true },
  { source: '/product-category/product/acr-acr/pa-deluxe/page/:path*', destination: '/driver/acr/deluxe', permanent: true },
  { source: '/product-category/product/acr-acr/pa-excellent/page/:path*', destination: '/driver/acr/excellent', permanent: true },
  { source: '/product-category/product/acr-acr/pa-fabulous/page/:path*', destination: '/driver/acr/fabulous', permanent: true },
  { source: '/product-category/product/curve/page/:path*', destination: '/driver/curve', permanent: true },
  { source: '/product-category/product/acr-acr/page/:path*', destination: '/driver/acr', permanent: true },
  { source: '/product-category/product/page/:path*', destination: '/driver', permanent: true },
  { source: '/product-category/type/subwoofer/page/:path*', destination: '/driver/subwoofer', permanent: true },
  { source: '/product-category/type/woofer/page/:path*', destination: '/driver/woofer', permanent: true },
  { source: '/product-category/type/tweeter/page/:path*', destination: '/driver/tweeter', permanent: true },
  { source: '/product-category/type/midbass/page/:path*', destination: '/driver/midbass', permanent: true },
  { source: '/product-category/type/midrange/page/:path*', destination: '/driver/midrange', permanent: true },
  { source: '/product-category/type/horn/page/:path*', destination: '/driver/horn', permanent: true },
  { source: '/product-category/type/ceiling/page/:path*', destination: '/driver/ceiling', permanent: true },
  { source: '/product-category/type/page/:path*', destination: '/driver', permanent: true },
  { source: '/product-category/product/acr-acr/pa-fabulous/subwoofer-pa-fabulous/page/:path*', destination: '/driver/acr/fabulous/subwoofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-fabulous/woofer-pa-fabulous/page/:path*', destination: '/driver/acr/fabulous/woofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-fabulous/midrange-pa-fabulous/page/:path*', destination: '/driver/acr/fabulous/midrange', permanent: true },
  { source: '/product-category/product/acr-acr/pa-fabulous/tweeter-pa-fabulous/page/:path*', destination: '/driver/acr/fabulous/tweeter', permanent: true },
  { source: '/product-category/product/acr-acr/pa-excellent/tweeter-pa-excellent/page/:path*', destination: '/driver/acr/excellent/tweeter', permanent: true },
  { source: '/product-category/product/acr-acr/pa-excellent/woofer-pa-excellent/page/:path*', destination: '/driver/acr/excellent/woofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-excellent/subwoofer-pa-excellent/page/:path*', destination: '/driver/acr/excellent/subwoofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-deluxe/subwoofer-pa-deluxe/page/:path*', destination: '/driver/acr/deluxe/subwoofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-premier-acr/woofer-pa-premier-acr/page/:path*', destination: '/driver/acr/premier/woofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-premier-acr/subwoofer-pa-premier-acr/page/:path*', destination: '/driver/acr/premier/subwoofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-classic/fullrange-pa-classic/page/:path*', destination: '/driver/acr/classic/full-range', permanent: true },
  { source: '/product-category/product/acr-acr/pa-black-magic/fullrange-pa-black-magic/page/:path*', destination: '/driver/acr/black-magic/full-range', permanent: true },
  { source: '/product-category/product/acr-acr/pa-acr/horn-pa-acr/page/:path*', destination: '/driver/acr/pro/horn', permanent: true },
  { source: '/product-category/product/acr-acr/pa-acr/tweeter-pa-acr/page/:path*', destination: '/driver/acr/pro/compression-driver', permanent: true },
  { source: '/product-category/product/acr-acr/pa-acr/fullrange-pa-acr/page/:path*', destination: '/driver/acr/pro/full-range', permanent: true },
  { source: '/product-category/product/acr-acr/pa-acr/woofer-pa-acr/page/:path*', destination: '/driver/acr/pro/woofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-acr/subwoofer-pa-acr/page/:path*', destination: '/driver/acr/pro/subwoofer', permanent: true },
  { source: '/product-category/product/curve/woofer-curve/page/:path*', destination: '/driver/curve/woofer', permanent: true },
  { source: '/product-category/product/acr-acr/pa-deluxe/woofer-pa-deluxe/page/:path*', destination: '/driver/acr/deluxe/woofer', permanent: true },
  { source: '/product-category/discontinued/page/:path*', destination: '/driver/discontinued', permanent: true },
  { source: '/product-category/discontinued/acr-discontinued/page/:path*', destination: '/driver/acr/pro/discontinued', permanent: true },
  { source: '/product-category/desibel/page/:path*', destination: '/driver/desibel', permanent: true },
  { source: '/product-category/desibel/desibel-tweeter/page/:path*', destination: '/driver/desibel/tweeter', permanent: true },
  { source: '/product-category/desibel/desibel-woofer/page/:path*', destination: '/driver/desibel/woofer', permanent: true },
  { source: '/product-category/desibel/desibel-subwoofer/page/:path*', destination: '/driver/desibel/subwoofer', permanent: true },
  { source: '/product-category/product/curve/fullrange-curve/page/:path*', destination: '/driver/curve/full-range', permanent: true },
  { source: '/product-category/type/fullrange/page/:path*', destination: '/driver/full-range', permanent: true },
  { source: '/product-category/desibel/desibel-desibel/page/:path*', destination: '/driver/desibel', permanent: true },
  { source: '/product-category/product/acr-acr/black-series/page/:path*', destination: '/driver/acr/black', permanent: true },
  { source: '/product-category/product/acr-acr/black-series/woofer-black-series/page/:path*', destination: '/driver/acr/black/woofer', permanent: true },
  { source: '/product-category/product/acr-acr/black-series/subwoofer-black-series/page/:path*', destination: '/driver/acr/black/subwoofer', permanent: true },
  { source: '/product-category/product/acr-acr/black-series/compression/page/:path*', destination: '/driver/acr/black/compression-driver', permanent: true },
  { source: '/product-category/product/acr-acr/black-series/fullrange-black-series/page/:path*', destination: '/driver/acr/black/full-range', permanent: true },
  { source: '/product-category/carousel_featured/page/:path*', destination: '/', permanent: true },

  //wp-sitemap-users-1.xml
  { source: '/a/author/sinarbaja', destination: '/berita', permanent: true },
];

// Generate redirects for each locale
const localizedRedirects = [];

for (const { source, destination, permanent } of baseRedirects) {
  localizedRedirects.push({
    source: `${source}`,
    destination: `${destination}`,
    permanent,
  });
}

module.exports = localizedRedirects;