export const allLocales = ['id', 'en']

export const allLocalesRoutes = [
    ['en', 'about-us'],
    ['en', 'catalogues'],
    ['en', 'contact'],
    ['en', 'comparison'],
    ['en', 'distributors'],
    ['en', 'news'],
    ['en', 'drivers'],
    ['en', 'spareparts'],
    ['id', 'tentang-kami'],
    ['id', 'katalog'],
    ['id', 'kontak'],
    ['id', 'komparasi'],
    ['id', 'distributor'],
    ['id', 'berita'],
    ['id', 'driver'],
    ['id', 'sparepart'],
]

export const allLocalesSubDrivers = [
    ['en', 'drivers', 'acr'],
    ['en', 'drivers', 'curve'],
    ['en', 'drivers', 'desibel'],
    ['en', 'drivers', 'subwoofer'],
    ['en', 'drivers', 'woofer'],
    ['en', 'drivers', 'full-range'],
    ['en', 'drivers', 'midrange'],
    ['en', 'drivers', 'tweeter'],
    ['en', 'drivers', 'discontinued'],
    
    ['id', 'driver', 'acr'],
    ['id', 'driver', 'curve'],
    ['id', 'driver', 'desibel'],
    ['id', 'driver', 'subwoofer'],
    ['id', 'driver', 'woofer'],
    ['id', 'driver', 'full-range'],
    ['id', 'driver', 'midrange'],
    ['id', 'driver', 'tweeter'],
    ['id', 'driver', 'discontinued'],

    ['en', 'spareparts', 'acr'],
    ['en', 'spareparts', 'curve'],
    ['en', 'spareparts', 'desibel'],
    ['en', 'spareparts', 'subwoofer'],
    ['en', 'spareparts', 'woofer'],
    ['en', 'spareparts', 'full-range'],
    ['en', 'spareparts', 'midrange'],
    ['en', 'spareparts', 'tweeter'],
    ['en', 'spareparts', 'discontinued'],
    
    ['id', 'sparepart', 'acr'],
    ['id', 'sparepart', 'curve'],
    ['id', 'sparepart', 'desibel'],
    ['id', 'sparepart', 'subwoofer'],
    ['id', 'sparepart', 'woofer'],
    ['id', 'sparepart', 'full-range'],
    ['id', 'sparepart', 'midrange'],
    ['id', 'sparepart', 'tweeter'],
    ['id', 'sparepart', 'discontinued'],
]

export const allLocalesSubSubDrivers = [
    ['en', 'drivers', 'acr', 'premier'],
    ['en', 'drivers', 'acr', 'deluxe'],
    ['en', 'drivers', 'acr', 'excellent'],
    ['en', 'drivers', 'acr', 'fabulous'],
    ['en', 'drivers', 'acr', 'pro'],

    ['en', 'drivers', 'desibel', 'subwoofer'],
    ['en', 'drivers', 'desibel', 'woofer'],
    ['en', 'drivers', 'desibel', 'midrange'],
    ['en', 'drivers', 'desibel', 'tweeter'],

    ['en', 'drivers', 'curve', 'woofer'],
    ['en', 'drivers', 'curve', 'full-range'],


    ['id', 'driver', 'acr', 'premier'],
    ['id', 'driver', 'acr', 'deluxe'],
    ['id', 'driver', 'acr', 'excellent'],
    ['id', 'driver', 'acr', 'fabulous'],
    ['id', 'driver', 'acr', 'pro'],

    ['id', 'driver', 'desibel', 'subwoofer'],
    ['id', 'driver', 'desibel', 'woofer'],
    ['id', 'driver', 'desibel', 'midrange'],
    ['id', 'driver', 'desibel', 'tweeter'],

    ['id', 'driver', 'curve', 'woofer'],
    ['id', 'driver', 'curve', 'full-range'],



    
    ['en', 'spareparts', 'acr', 'premier'],
    ['en', 'spareparts', 'acr', 'deluxe'],
    ['en', 'spareparts', 'acr', 'excellent'],
    ['en', 'spareparts', 'acr', 'fabulous'],
    ['en', 'spareparts', 'acr', 'pro'],
    
    ['en', 'spareparts', 'desibel', 'subwoofer'],
    ['en', 'spareparts', 'desibel', 'woofer'],
    ['en', 'spareparts', 'desibel', 'midrange'],
    ['en', 'spareparts', 'desibel', 'tweeter'],

    ['en', 'spareparts', 'curve', 'woofer'],
    ['en', 'spareparts', 'curve', 'full-range'],
    
    
    ['id', 'sparepart', 'acr', 'premier'],
    ['id', 'sparepart', 'acr', 'deluxe'],
    ['id', 'sparepart', 'acr', 'excellent'],
    ['id', 'sparepart', 'acr', 'fabulous'],
    ['id', 'sparepart', 'acr', 'pro'],
    
    ['id', 'sparepart', 'desibel', 'subwoofer'],
    ['id', 'sparepart', 'desibel', 'woofer'],
    ['id', 'sparepart', 'desibel', 'midrange'],
    ['id', 'sparepart', 'desibel', 'tweeter'],

    ['id', 'sparepart', 'curve', 'woofer'],
    ['id', 'sparepart', 'curve', 'full-range'],
]

export const allLocalesSubSubSubDrivers = [
    ['en', 'drivers', 'acr', 'premier', 'subwoofer'],
    ['en', 'drivers', 'acr', 'premier', 'woofer'],
    ['en', 'drivers', 'acr', 'deluxe', 'subwoofer'],
    ['en', 'drivers', 'acr', 'deluxe', 'woofer'],
    ['en', 'drivers', 'acr', 'excellent', 'subwoofer'],
    ['en', 'drivers', 'acr', 'excellent', 'woofer'],
    ['en', 'drivers', 'acr', 'excellent', 'tweeter'],
    ['en', 'drivers', 'acr', 'fabulous', 'subwoofer'],
    ['en', 'drivers', 'acr', 'fabulous', 'woofer'],
    ['en', 'drivers', 'acr', 'fabulous', 'midrange'],
    ['en', 'drivers', 'acr', 'fabulous', 'tweeter'],
    ['en', 'drivers', 'acr', 'fabulous', 'discontinued'],
    ['en', 'drivers', 'acr', 'pro', 'subwoofer'],
    ['en', 'drivers', 'acr', 'pro', 'woofer'],
    ['en', 'drivers', 'acr', 'pro', 'full-range'],
    ['en', 'drivers', 'acr', 'pro', 'midrange'],
    ['en', 'drivers', 'acr', 'pro', 'tweeter'],
    ['en', 'drivers', 'acr', 'pro', 'discontinued'],

    ['en', 'spareparts', 'acr', 'premier', 'subwoofer'],
    ['en', 'spareparts', 'acr', 'pro', 'subwoofer'],
    ['en', 'spareparts', 'acr', 'excellent', 'subwoofer'],
    ['en', 'spareparts', 'acr', 'deluxe', 'subwoofer'],
    ['en', 'spareparts', 'acr', 'fabulous', 'subwoofer'],
    ['en', 'spareparts', 'acr', 'premier', 'woofer'],
    ['en', 'spareparts', 'acr', 'deluxe', 'woofer'],
    ['en', 'spareparts', 'acr', 'excellent', 'woofer'],
    ['en', 'spareparts', 'acr', 'pro', 'woofer'],
    ['en', 'spareparts', 'acr', 'fabulous', 'woofer'],
    ['en', 'spareparts', 'acr', 'pro', 'full-range'],
    ['en', 'spareparts', 'acr', 'fabulous', 'midrange'],
    ['en', 'spareparts', 'acr', 'pro', 'midrange'],
    ['en', 'spareparts', 'acr', 'excellent', 'tweeter'],
    ['en', 'spareparts', 'acr', 'fabulous', 'tweeter'],
    ['en', 'spareparts', 'acr', 'pro', 'tweeter'],
    ['en', 'spareparts', 'acr', 'fabulous', 'discontinued'],
    ['en', 'spareparts', 'acr', 'pro', 'discontinued'],





    ['id', 'driver', 'acr', 'premier', 'subwoofer'],
    ['id', 'driver', 'acr', 'premier', 'woofer'],
    ['id', 'driver', 'acr', 'deluxe', 'subwoofer'],
    ['id', 'driver', 'acr', 'deluxe', 'woofer'],
    ['id', 'driver', 'acr', 'excellent', 'subwoofer'],
    ['id', 'driver', 'acr', 'excellent', 'woofer'],
    ['id', 'driver', 'acr', 'excellent', 'tweeter'],
    ['id', 'driver', 'acr', 'fabulous', 'subwoofer'],
    ['id', 'driver', 'acr', 'fabulous', 'woofer'],
    ['id', 'driver', 'acr', 'fabulous', 'midrange'],
    ['id', 'driver', 'acr', 'fabulous', 'tweeter'],
    ['id', 'driver', 'acr', 'fabulous', 'discontinued'],
    ['id', 'driver', 'acr', 'pro', 'subwoofer'],
    ['id', 'driver', 'acr', 'pro', 'woofer'],
    ['id', 'driver', 'acr', 'pro', 'full-range'],
    ['id', 'driver', 'acr', 'pro', 'midrange'],
    ['id', 'driver', 'acr', 'pro', 'tweeter'],
    ['id', 'driver', 'acr', 'pro', 'discontinued'],

    ['id', 'sparepart', 'acr', 'premier', 'subwoofer'],
    ['id', 'sparepart', 'acr', 'pro', 'subwoofer'],
    ['id', 'sparepart', 'acr', 'excellent', 'subwoofer'],
    ['id', 'sparepart', 'acr', 'deluxe', 'subwoofer'],
    ['id', 'sparepart', 'acr', 'fabulous', 'subwoofer'],
    ['id', 'sparepart', 'acr', 'premier', 'woofer'],
    ['id', 'sparepart', 'acr', 'deluxe', 'woofer'],
    ['id', 'sparepart', 'acr', 'excellent', 'woofer'],
    ['id', 'sparepart', 'acr', 'pro', 'woofer'],
    ['id', 'sparepart', 'acr', 'fabulous', 'woofer'],
    ['id', 'sparepart', 'acr', 'pro', 'full-range'],
    ['id', 'sparepart', 'acr', 'fabulous', 'midrange'],
    ['id', 'sparepart', 'acr', 'pro', 'midrange'],
    ['id', 'sparepart', 'acr', 'excellent', 'tweeter'],
    ['id', 'sparepart', 'acr', 'fabulous', 'tweeter'],
    ['id', 'sparepart', 'acr', 'pro', 'tweeter'],
    ['id', 'sparepart', 'acr', 'fabulous', 'discontinued'],
    ['id', 'sparepart', 'acr', 'pro', 'discontinued'],
]